istanbulWeb/Models/Giris.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace istanbulWeb.Models
{
    public class Giris
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }

    }
}

istanbulWeb/Controllers/CevreDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using istanbulWeb.Models;
using istanbulWeb.Models.Managers;

namespace istanbulWeb.Controllers
{
    public class CevreDataController : Controller
    {
        // GET: CevreData
        public ActionResult Table1()
        {
            webistanbulContext context = new webistanbulContext();
            List<dogalgazTuketimverileris> tbl1 = context.dogalgazTuketimverileri.ToList();
            return View(tbl1);
        }
       
        public ActionResult Table3()
        {
            webistanbulContext context = new webistanbulContext();
            List<ToplananKatiAtikMiktarlaris> tbl3 = context.ToplananKatiAtikMiktarlari.ToList();
            return View(tbl3);
        }
        public ActionResult Table4()
        {
            webistanbulContext context = new webistanbulContext();
            List<GeriKazanilanatikMiktars> tbl4 = context.GeriKazanilanatikMiktar.ToList();
            return View(tbl4);
        }
        public ActionResult Table5()
        {
            webistanbulContext context = new webistanbulContext();
            List<GemiAtikTuruveMiktaris> tbl5 = context.GemiAtikTuruveMiktari.ToList();
            return View(tbl5);
        }
        public ActionResult Table6()
        {
            webistanbulContext context = new webistanbulContext();
            List<ToplamatikGeriKazanimOranis> tbl6 = context.ToplamatikGeriKazanimOrani.ToList();
            return View(tbl6);
        }
        public ActionResult Table7()
        {
            webistanbulContext context = new webistanbulContext();
            List<YeniYapilanYesilAlanMiktaris> tbl7 = context.YeniYapilanYesilAlanMiktari.ToList();
            return View(tbl7);
        }
        public ActionResult Table8()
        {
            webistanbulContext context = new webistanbulContext();
            List<GunesUretimMiktarlaris> tbl8 = context.GunesUretimMiktarlari.ToList();
            return View(tbl8);
        }

    }
}

istanbulWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using istanbulWeb.Models;

namespace istanbulWeb.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            List<ReadMore> haberler = new List<ReadMore>
            {
                new ReadMore(){ResimYolu="../iwpProje/covid.jpg",
                    Baslik="Covid-19",
                    Paragraf="COVID-19 verileri resmi kanallardan ve ayrıntılı olarak verilmelidir! Klinik ve radyolojik olarak COVID-19 tanısı alan hastalar aksi kanıtlanıncaya kadar COVID-19 kabul edilerek gerekli önlemler alınmalıdır!TC Sağlık Bakanllığının Covid-19 Bilgilendirme Sayfasına gitmek için butona tıklayın.",
                    Link="https://covid19.saglik.gov.tr/"},
                new ReadMore(){ResimYolu="../iwpProje/ibb.png",Baslik="İstanbul Büyükşehir Belediyesi",Paragraf="İstanbul Büyükşehir Belediyesinin resmi sitesine gitmek için tıklayın.",Link="https://www.ibb.istanbul/"},
                new ReadMore(){ResimYolu="../iwpProje/hava.jpg",Baslik="Hava Durumu",Paragraf="İstanbul İçin Detaylı Hava Durumu Tahminini Görmek için tıklayın.",Link="https://www.mgm.gov.tr/tahmin/il-ve-ilceler.aspx?il=Istanbul"},
                new ReadMore(){ResimYolu="../iwpProje/iett.jpg",Baslik="İETT",Paragraf="Otobüs Saatlerinizi öğrenmek için tıklayın.",Link="https://www.iett.istanbul/"}

            };
            return View(haberler);
        }
        public ActionResult Giris()
        {

            return View();
        }
        public ActionResult Data()
        {
            return View();
        }
        public ActionResult Egitim()
        {

            List<Read> read = new List<Read>
            {
            new Read(){ResimYolu = "../iwpProje/Gurak1.jpg",
            Baslik = "Eğitim",
            Paragraf = "Elimizdeki verilere bakıldığında okuma yazma bilen kişi sayının yeterli olmadığını görmekteyiz. Özellikle okuma yazma bilen kadınların erkeklere göre azınlıkta olduğu görülüyor. Oysa ki kadın eğitimi ile ilgili yapılan çalışmaların çoğunda, kadın eğitiminin erkek eğitiminden daha önemli olduğu vurgulanmaktadır.Çünkü bir kadının eğitilmesi demek aynı zamanda aile içerisinde baba da dahil diğer çocukların görgülerinin artırılması demektir.Annenin daha uzun süreli bir eğitim düzeyine sahip olması aile içerisinde hem erkek hem de kız çocuğunun daha uzun süreli bir eğitimden geçirilmesinin imkanlarını yaratır." ,
            Paragraf2="Kadınlarına gerekli eğitim imkanlarını hazırlamayan,öğretim sürelerini kısa tutan toplumlarda kadınların yetkin ve toplumsal saygınlığı olan meslekleri elde etmesi oldukça zor olacaktır.Bunun sonucunda bu tür toplumlarda “Kültürel Sermaye” birikiminin az olmasını sağlayacak ve aile içerisinde çocuğun olumlu şekilde sosyalleşmesini,okul öncesi bir takım bilgi ve beceriye sahip olmasını,öğrenmeye hazır bulunuşluk düzeyini olumsuz şekilde etkileyecektir. Bu yüzden eğitime önem verilmelidir özellikle de kız çocuklarının eğitimine.",
            Kaynak = "https://dergipark.org.tr/tr/download/article-file/118029"
            }

            };

            return View(read);
        }
        public ActionResult Ulasim()
        {
            List<Read> read = new List<Read>
            {
                new Read(){ResimYolu="../iwpProje/istanbul-trafigi.jpg",Baslik="İstanbul Trafiği",Paragraf=" İstanbul yaklaşık 17 milyon nüfusuyla Türkiye’ en kalabalık olan ilidir. İki kıta olan Asya ve Avrupa’yı birbirine bağlaması"+
                "ve balkanlara bu şehrimiz üzerinden geçiş sağlanması ile tarih boyunca önemini korumuştur. Tarih çağlar boyunca birçok uygarlığa"+
                "ev sahipliği yapan İstanbul, hep gözde şehir olmuştur. Çok fazla imparatorluk’ ada başkentlik yapmıştır. Şehirin önemi böylece artmakta"+
                " çünkü, tarihi kalıntılar ve gezilecek yerlerin çok olması turist nufüsuda artırmaktadır. Yaz, kış demeden gelen turistler özellikle, Ayasofya"+
                " camii ve Sultan Ahmet Camiini gezmektedir. Yurt içi ve yurt dışı turist akımını da düşünürsek inanılmaz bir insan kalabalığı karşımıza çıkmaktadır.",
                Paragraf2= "Nüfusun bu kadar kalabalık olması bir çok problemi de beraberinde getirmektedir. İstanbul’ un en büyük sorunu trafik olarak karşımıza çıkmaktadır."+
                " İstanbul trafiğine her geçen bir önlem daha alınmasına rağmen bu sorun bir türlü çözülememektedir. İstanbul şehir içi ulaşımda bir çok tramvay, metro,"+
                " İETT ( İstanbul Elektrikli Tramvay ve Tünel işletmeleri), metrobüs, ido ve vapur seferleri yapılmakta amaç herkesin hızlı ve güvenli bir şekilde ulaşımını"+
                " sağlamaktır. Saymış olduğumuz ulaşım araçlarından birinin aksaması tüm trafiği alt üst etmektedir. Sabahın erken saatlerinde başlayan İstanbul trafiği"+
                " öğlen biraz nefes alsada akşam iş çıkış saatlerinde herkesin bu trafiğe yakalanmasına sebep olmaktadır. Özellikle şahsi taksilerle ulaşımını gerçekleştirenler"+
                " saatlerce yolda beklemek zorunda kaldıkları görülmektedir.",
                    Kaynak="https://www.bilgicik.com/yazi/istanbulda-trafik-problemi/"}

            };
            return View(read);
        }
        public ActionResult Cevre()
        {
            List<Read> read = new List<Read>
            {
                new Read(){ResimYolu="../iwpProje/eniro.jpg",
                    Baslik="Doğamızı Koruyalım!",Paragraf="Doğaya bıraktığımız atıklar yüzünden yakında Dünyamız yaşanmayacak hale gelecek. Yukarıda ki verilerde de gördüğünüz üzeri istanbulda da yılda doğaya bırakılan atık atık miktarı çok fazla. Özelliklede denizlere atılan atıklar yüzünden denizler artık girilemeyecek durumda ve bu atıklar yüzünden deniz canlıları da zarar görmektedir.Bu şekilde devam ederse malesef dünya yaşanmaycak hale gelecek bunun olmaması için herkesin bireysel olarak yapabileceği bazı şeyler:",
                Paragraf2=" Tüketirken tekrar düşünülmeli, gereksiz tüketimden kaçınılmalıdır." +
                " Tükettiğimiz ürünleri tercih ederken çevresel etkilerine dikkat edilmeli ve seçimler bilinçli bir şekilde yapılmalıdır." +
                " Çöpler, çöp poşetinin ağzını sıkıca bağlandıktan sonra çöp kutusuna atılmalıdır.Ormanlar korunmalıdır.Ağaçlara zarar verilmemelidir." +
                " Çimlerin üzerinde ateş yakılmamalıdır.Hayvanlara zarar vermekten kaçınılmalıdır." +
                " Denizler kirletilmemelidir.Evcil hayvanların atıkları temizlenmelidir." +
                " Çevremiz sahiplenmeli, değeri ve önemi çocuklara öğretilmeli, büyüklere anlatılmalıdır.Enerji tasarrufu yapılmalıdır." +
                " Biten piller pil kutusuna atılmalıdır.Piknikten sonra ateş söndürülmeli ve asla yerde çöp bırakılmamalıdır." +
                " Kâğıt, teneke, cam, pil gibi geri dönüşümü olan maddeler geri dönüşüm kutularına atılmalıdır.Egzozlu taşıtlar fazlalaşmamalıdır." +
                " Başta su olmak üzere her konuda israftan kaçınılmalıdır.ürünleri özellikle de saç sprayleri ve deodorantlar fazla kullanılmamalıdır.",
                    Kaynak="https://sites.google.com/site/nurcancakalsitesi/cevreyi-korumak-icin-neler-yapmaliyiz" }
            };


            return View(read);
        }
        public ActionResult DogalAfet()
        {
            List<Read> read = new List<Read>
            {
                new Read(){ResimYolu="../iwpProje/deprem.jpg",Baslik="Deprem Anında Yapılması Gerekenler",Paragraf="Doğal afetler yaşamımızı derinden etkilemektedir. Özelliklede ülkemizde sık yaşanan deprem bu afetleri en az hasarla atlatmak  için aşağıdakiler yapılabilir:" +
                "C. DEPREM SIRASINDA ALINACAK ÖNLEMLER",
                   Paragraf2= " I. Bina İçerisinde"+
                    " 1- Kesinlikle panik yapmamalıyız. Sabitlenmemiş dolap, raf, pencere vb. eşyalardan uzak"+
                    " durmalıyız. Varsa sandalyelerle desteklenmiş masa yanına veya dolgun ve hacimli koltuk, kanepe, içi"+
                    " dolu sandık gibi koruma sağlayabilecek eşya yanına çömelmeli veya uzanmalıyız. Başımızı iki"+
                    " elimizin arasında alarak veya bir koruyucu (yastık, kitap vb) malzeme ile korumalıyız. ÇÖK-KAPANTUTUN doğru davranış şeklini uygulayarak sarsıntı geçene dek beklemeliyiz"+
                    " 2- Tekerlekli sandalyede isek tekerlekleri kilitleyerek başımızı ve boynumuzu korumaya"+
                    " almalıyız."+
                    " 3- Mutfak, imalathane, laboratuvar gibi is aletlerinin bulunduğu yerlerde; ocak, fırın ve bu gibi"+
                    " cihazları kapatmalıyız. Dökülebilecek malzeme ve maddelerden uzaklaşmalıyız.Birinci maddede"+
                    " belirtildiği şekilde kendimizi korumalıyız."+
                    " 4 - Sarsıntı geçtikten sonra elektrik, gaz ve su vanalarını kapatmalıyız.Soba ve ısıtıcıları"+
                    " söndürmeliyiz.Diğer güvenlik önlemlerini almalıyız ve daha önceden hazırlanmış acil durum çantası"+
                    " ile gerekli olan eşya ve malzemeyi yanımıza alarak derhal binayı daha önce tespit ettiğimiz yoldan"+
                    " terk edip toplanma bölgesine gitmeliyiz."+
                    " 5 - Merdiven, balkon, koridor ve geniş sahanlı yerlerden, kolonlardan ve pencerelerden"+
                    " uzaklaşmalıyız."+
                    " 6 - Okulda isek sınıfta kalarak sağlamsa sıra yanına birinci maddede belirtildiği şekilde ÇÖKKAPAN - TUTUN hareketini yaparak başımızı korumalıyız."+
                    " 7 - Kesinlikle asansör kullanmamalıyız. Asansörde isek kat çıkış düğmesine basarak asansörü"+
                    "  terk etmeliyiz."+
                    "  II.Bina Dışında"+
                    " 1 - Enerji hatlarından, diğer binalardan ve duvar diplerinden uzaklaşmalıyız. Açık arazide"+
                    " çömelerek etraftan gelen tehlikelere karşı hazırlıklı olmalıyız."+

istanbulWeb/Controllers/NufusDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using istanbulWeb.Models;
using istanbulWeb.Models.Managers;

namespace istanbulWeb.Controllers
{
    public class NufusDataController : Controller
    {
        // GET: NufusData
        public ActionResult Table1()
        {
            webistanbulContext context = new webistanbulContext();
            List<NufusBilgileris> tbl1 = context.NufusBilgileri.ToList();
            return View(tbl1);
        }
        public ActionResult Table2()
        {
            webistanbulContext context = new webistanbulContext();
            List<HalkHaneBuyukluguSayisis> tbl2 = context.HalkHaneBuyukluguSayisi.ToList();
            return View(tbl2);
        }
    }
}

istanbulWeb/Controllers/SporDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using istanbulWeb.Models;
using istanbulWeb.Models.Managers;

namespace istanbulWeb.Controllers
{
    public class SporDataController : Controller
    {
        // GET: SporData
        public ActionResult Table1()
        {
            webistanbulContext context = new webistanbulContext();
            List<SporOrganizasyonuveSporcuSayilaris> spor = context.SporOrganizasyonuveSporcuSayilari.ToList();

            //var spor = context.SporOrganizasyonuveSporcuSayilari.ToList();
            return View(spor);
        }
    }
}

istanbulWeb/Views/Home/Cevre.cshtml
@model List<istanbulWeb.Models.Read>
<!-- ***************************************************GRAFİKLER**********************************************************************-->
@Html.Partial("_Grafik")
<div id="myDIV">
    <div class="row" id="grafikler">
        <div class="col-sm-5" id="0">
            <div class="w2-card-4">
                <a href="@Url.Action("Table1","CevreData")" id="link">
                    <img src="~/iwpProje/Grafikler/ilce_baznda_yllara_gore_dogalgaz_tuketimi.png"
                         class="card-img-top"
                         alt="resim" />
                    <h2>İlçe Bazında Yıllara Göre Doğalgaz Tüketimi</h2>
                </a>
            </div>
        </div>
        <div class="col-sm-5" id="1">
            <div class="w2-card-4">
                <a href="@Url.Action("Table2","CevreData")" id="link">
                    <img src="~/iwpProje/grafikler/baraj doluluk oranì.PNG"
                         class="card-img-top"
                         alt="resim" />
                    <h2>Baraj Doluluk Oranları</h2>
                </a>
            </div>
        </div>
        <div class="col-sm-5" id="2">
            <div class="w2-card-4">
                <a href="@Url.Action("Table3","CevreData")" id="link">
                    <img src="~/iwpProje/Grafikler/Deniz yüzeyi ve kìyìlardan toplanan katì atìk  miktarì.PNG"
                         class="card-img-top"
                         alt="resim" />
                    <h2>
                        Deniz Yüzeyi, Kıyı ve Plajlardan Toplanan Katı Atık Miktarı
                    </h2>
                </a>
            </div>
        </div>
        <div class="col-sm-5" id="3">
            <div class="w2-card-4">
                <a href="@Url.Action("Table4","CevreData")" id="link">
                    <img src="~/iwpProje/Grafikler/gemi kaynaklì petrol türevli atìklarìn geri kazanìlan miktar.PNG"
                         class="card-img-top"
                         alt="resim" />
                    <h2>
                        Gemi Kaynaklı Petrol Türevli Atıkların Susuzlaştırılmasıyla Geri
                        Kazanılan Miktar
                    </h2>
                </a>
            </div>
        </div>
        <div class="col-sm-5" id="4">
            <div class="w2-card-4">
                <a href="@Url.Action("Table5","CevreData")" id="link">
                    <img src="~/iwpProje/Grafikler/Gemilerden toplanan atìklar.PNG"
                         class="card-img-top"
                         alt="resim" />
                    <h2>Gemilerden Toplanan Atık Miktarı ve Türü</h2>
                </a>

            </div>
        </div>

        <div class="col-sm-5" id="5">
            <div class="w2-card-4">
                <a href="@Url.Action("Table6","CevreData")" id="link">
                    <img src="~/iwpProje/Grafikler/toplam atìk geri kazanìm  miktarì.PNG"
                         class="card-img-top"
                         alt="resim" />
                    <h2>Toplam Atık Geri Kazanım Miktarı</h2>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- ReadMore Start-->
@Html.Partial("_Read")

istanbulWeb/Views/Home/Data.cshtml
<!------------------------------------------------------------------------------------------------------------------------->
<div class="container" style="font-size: 1.3rem" id="myDIV">
    <h2>Data</h2>
    <p>
        <strong>Note:</strong> The <strong>data-parent</strong> attribute makes
        sure that all collapsible elements under the specified parent will be
        closed when one of the collapsible item is shown.
    </p>
    <div id="accordion">
        <div class="card">
            <div class="card-header">
                <a class="card-link"
                   data-toggle="collapse"
                   href="#collapseOne"
                   style="color: black">
                    Eğitim
                </a>
            </div>
            <div id="collapseOne" class="collapse show" data-parent="#accordion">
                <div class="card-body">
                    <ul>
                        <li>
                            @Html.ActionLink("Okuma Yazma Bilen-Bilmeyen Kişi Sayısı", "Table1", "EgitimData")
                        </li>
                        <li>
                            @Html.ActionLink("İstanbul İlköğretim İlkokul ve Ortaokul Öğrenci Sayıları", "Table2", "EgitimData")

                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <a class="collapsed card-link"
                   data-toggle="collapse"
                   href="#collapseTwo"
                   style="color: black">
                    Ulaşım
                </a>
            </div>
            <div id="collapseTwo" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <ul>
                        <li>
                            @Html.ActionLink("Deniz İşletmeleri Bazında Max Yolculuk Sayısı", "Table1", "UlasimData")

                        </li>
                        <li>
                            @Html.ActionLink("Karayolları bazında araç ve hat sayısı", "Table2", "UlasimData")

                        </li>
                        <li>
                            @Html.ActionLink("Karayolları bazında maksimum yolculuk sayısı", "Table3", "UlasimData")

                        </li>
                        <li>
                            @Html.ActionLink("İstanbulkart Dolum Merkezi Bilgileri", "Table4", "UlasimData")


                        </li>
                        <li>
                            @Html.ActionLink("Raylı Sistemlere Ait İnternet Siteleri", "Table5", "UlasimData")

                        </li>
                        <li>
                            @Html.ActionLink("Raylı Sistemlere Ait Tamamlanmış Şantiye Bilgileri", "Table6", "UlasimData")

                        </li>
                        <li>
                            @Html.ActionLink("Raylı Sistemler Hat Bazlı Sefer Sayıları", "Table7", "UlasimData")


                        </li>
                        <li>
                            @Html.ActionLink("Yolculuk Türü Bazında Yolcu Sayısı", "Table8", "UlasimData")

                        </li>
                        <li>
                            @Html.ActionLink("İstasyonlar", "Table9", "UlasimData")

                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <a class="collapsed card-link"
                   data-toggle="collapse"
                   href="#collapseThree"
                   style="color: black">
                    Çevre
                </a>
            </div>
            <div id="collapseThree" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <ul>
                        <li>
                            @Html.ActionLink("İlçe Bazında Yıllara Göre Doğalgaz Tüketimi", "Table1", "CevreData")

                        </li>
                        <li>
                            @Html.ActionLink("Baraj Doluluk Oranları", "Table2", "CevreData")


                        </li>
                        <li>
                            @Html.ActionLink("Deniz Yüzeyi, Kıyı ve Plajlardan Toplanan Katı Atık Miktarı", "Table3", "CevreData")


                        </li>
                        <li>
                            @Html.ActionLink("Gemi Kaynaklı Petrol Türevli Atıkların Susuzlaştırılmasıyla Geri Kazanılan Miktar", "Table4", "CevreData")


                        </li>
                        <li>
                            @Html.ActionLink("Gemilerden Toplanan Atık Miktarı ve Türü", "Table5", "CevreData")

                        </li>

                        <li>
                            @Html.ActionLink("Toplam Atık Geri Kazanım Miktarı", "Table6", "CevreData")

                        </li>
                        <li>
                            @Html.ActionLink("İstanbul Genel Yeşil Alan Bilgiler 2004-2019", "Table7", "CevreData")

                        </li>
                        <li>
                            @Html.ActionLink("İstanbul Güneş Enerji Santralleri Üretim Miktarları", "Table8", "CevreData")

                        </li>

                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <a class="card-link"
                   data-toggle="collapse"
                   href="#collapseFive"
                   style="color: black">
                    Nüfus
                </a>
            </div>
            <div id="collapseFive" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <ul>
                        <li>
                            @Html.ActionLink("Belediye Nüfusları", "Table1", "NufusData")
                        </li>
                        <li>
                            @Html.ActionLink("Ortalama Hane Halkı Büyüklüğü", "Table2", "NufusData")

                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <a class="card-link"
                   data-toggle="collapse"
                   href="#collapseSix"
                   style="color: black">
                    Kültür
                </a>
            </div>
            <div id="collapseSix" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <ul>
                        <li>
                            @Html.ActionLink("2018-2020 Oyun Bazlı İzleyici Sayısı, Seans Sayısı ve Salon Doluluk Oranı", "Table1", "KulturData")

                        </li>
                        <li>
                            @Html.ActionLink("Yıl Bazında Oyun Sayısı", "Table2", "KulturData")

                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <a class="card-link"
                   data-toggle="collapse"
                   href="#collapseSeven"
                   style="color: black">
                    Doğal Afet
                </a>
            </div>
            <div id="collapseSeven" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <ul>
                        <li>
                            @Html.ActionLink("İtfaiye Konum Verisi", "Table1", "DogalAfetData")

                        </li>
                        <li>
                            @Html.ActionLink("Yangın İstatistikleri", "Table2", "DogalAfetData")

                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <a class="card-link"
                   data-toggle="collapse"
                   href="#collapseNine"
                   style="color: black">
                    Spor
                </a>
            </div>
            <div id="collapseNine" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <ul>
                        <li>
                            @Html.ActionLink("Spor Organizasyonları ve Sporcu Sayısı", "Table1", "SporData")

                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

istanbulWeb/Views/Home/DogalAfet.cshtml
@model List<istanbulWeb.Models.Read>



<!-- ReadMore Start-->
@Html.Partial("_Read")

istanbulWeb/Views/Home/Egitim.cshtml
@model List<istanbulWeb.Models.Read>

<!-- ***************************************************GRAFİKLER**********************************************************************-->
@Html.Partial("_Grafik")
<div id="myDIV">
    <div class="row" id="grafikler">
        <div class="col-sm-5" id="0">
            <div class="w2-card-4">
                @Html.ActionLink("Okuma Yazma Bilen-Bilmeyen Kişi Sayısı", "Table1", "EgitimData")
                <a href="@Url.Action("Table1","EgitimData")" id="link">
                    <img src="../iwpProje/Grafikler/Okuma_yazma_bilen_bilmeyen_kisi.png"
                         class="card-img-top"
                         alt="resim" />
                    <h2>Okuma Yazma Bilen-Bilmeyen Kişi Sayısı</h2>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- ReadMore Start-->
@Html.Partial("_Read")

istanbulWeb/Views/Home/Kultur.cshtml
@model List<istanbulWeb.Models.Read>

<!-- ***************************************************GRAFİKLER**********************************************************************-->

<!-- ReadMore Start-->
@Html.Partial("_Read")

istanbulWeb/Views/Home/Nufus.cshtml
@model List<istanbulWeb.Models.Read>

<!-- ***************************************************GRAFİKLER**********************************************************************-->
@Html.Partial("_Grafik")
<div id="myDIV">
    <div class="row" id="grafikler">
        <div class="col-sm-5" id="0">
            <div class="w2-card-4">
                <a href="@Url.Action("Table1","NufusData")" id="link">
                    <img src="~/iwpProje/Grafikler/belediye_nufuslar.png"
                         class="card-img-top"
                         alt="resim" />
                    <h2>Belediye Nüfusları</h2>
                </a>
            </div>
        </div>
        <div class="col-sm-5" id="1">
            <div class="w2-card-4">
                <a href="@Url.Action("Table2","NufusData")" id="link">
                    <img src="~/iwpProje/Grafikler/Ortalama hane halkì büyüklüºü.PNG"
                         class="card-img-top"
                         alt="resim" />
                    <h2>Ortalama Hane Halkı Büyüklüğü</h2>
                </a>
            </div>
        </div>

    </div>
</div>

<!-- ReadMore Start-->
@Html.Partial("_Read")

istanbulWeb/Views/Home/Spor.cshtml
@model List<istanbulWeb.Models.Read>

<!-- ***************************************************GRAFİKLER**********************************************************************-->
@Html.Partial("_Grafik")
<div id="myDIV">
    <div class="row" id="grafikler">
        <div class="col-sm-5" id="0">
            <div class="w2-card-4">
                <a href="@Url.Action("Table1","SporData")" id="link">
                    <img src="~/iwpProje/grafikler/spor organizasyonlarì ve sporcu sayìlarì.PNG"
                         class="card-img-top"
                         alt="resim" />
                    <h2>Spor Organizasyonları ve Sporcu Sayısı</h2>
                </a>
            </div>
        </div>

    </div>
</div>

<<!-- ReadMore Start-->
@Html.Partial("_Read")